name: Lint

on:
  pull_request:
  workflow_dispatch:

jobs:
  setup:
    name: dependencies-cache
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "yarn"

      - run: yarn install --frozen-lockfile

  lint:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Biome Link
        run: pnpm run check
