name: Lint

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 📥 dependency install with cache
        uses: ./.github/actions/yarn-install

      - name: Biome Link
        run: yarn run check
