name: Lint

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  setup:
    name: project-setup
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: 📥 Monorepo install
        uses: ./.github/actions/yarn-install

  lint:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Biome Link
        run: pnpm run check
